apiVersion: v1
kind: Pod
metadata:
  name: Inmarapp
  labels:
    app: Inmarapp
spec:
  containers:
  - name: Inmarapp
    image: gopinadh/Inmarapp
    ports:
    - name: Inmarapp-port
      containerPort: 8080
