apiVersion: v1
kind: Service
metadata:
  name: Inmarapp-service
spec:
  ports:
  - port: 30001
    nodePort: 30001
    targetPort: Inmarapp-port
    protocol: TCP
  selector:
    app: Inmarapp
  type: NodePort
