apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: Inmarapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: Inmarapp
    spec:
      containers:
      - name: Inmarapp
        image: gopinadh/Inmarapp
        ports:
        - name: Inmarapp-port
          containerPort: 8080
