apiVersion: v1
kind: Pod
metadata:
  name: Inmardb
  labels:
    app: Inmardb
spec:
  containers:
  - name: Inmardb
    image: gopinadh/Inmardb
    ports:
    - name: Inmardb-port
      containerPort: 3306

    env:
     - name: MYSQL_ROOT_PASSWORD
       value: "vprodbpass"

